### ISSUE TITLE
import error in example

### ISSUE THREAD

**Issue by sohan99** [HarryMWinters/fastapi-oidc#20]
`from fastapi_oidc import IDToken`
cant find the IDToken.

I could use it as bellow
`from fastapi_oidc.types import IDToken`
<img width="439" alt="Screenshot 2021-08-14 at 12 58 50 PM" src="https://user-images.githubusercontent.com/9268514/129438836-431d0b67-9bac-42d0-87ce-304271884866.png">

**Comment by HarryMWinters** [comment]
Whoops! Thanks @sohan99. I'll expose `IDToken` (and other types) in the project root. In the meantime `from fastapi_oidc.types import IDToken` should work.

**Comment by HarryMWinters** [comment]
Patched and release in v0.0.8 @sohan99 😺 Thanks for the heads up!
