### ISSUE TITLE
Audience in token can be a list too

### ISSUE THREAD

**Issue by samedii** [HarryMWinters/fastapi-oidc#27]
Multiple types allowed is painful
> aud
REQUIRED. Audience(s) that this ID Token is intended for. It MUST contain the OAuth 2.0 client_id of the Relying Party as an audience value. It MAY also contain identifiers for other audiences. In the general case, the aud value is an array of case sensitive strings. In the common special case when there is one audience, the aud value MAY be a single case sensitive string.
https://openid.net/specs/openid-connect-core-1_0.html

**Comment by hassanrazakhalid** [comment]
Yes same issue. I can not validate token because audiance is list
