### ISSUE TITLE
Some optional values are required

### ISSUE THREAD

**Issue by zefciu** [HarryMWinters/fastapi-oidc#9]
After running the simple flow with Google as authentication provider I get this error:

```
pydantic.error_wrappers.ValidationError: 6 validation errors for IDToken
name
  field required (type=value_error.missing)
preferred_username
  field required (type=value_error.missing)
auth_time
  field required (type=value_error.missing)
ver
  field required (type=value_error.missing)
amr
  field required (type=value_error.missing)
idp
  field required (type=value_error.missing)
```

Indeed these fields are not present in the JWT token that was generated by Google, but they are not listed as required in the spec. I believe they are always present in okta, but should be made optional to ensure compatibility with other providers.

**Comment by HarryMWinters** [comment]
Thanks for bringing this up @zefciu! I was on vacation but I'll update the IDToken model this week. And of course, issue #1 points out an easy way to bypass this library completely.
